### ISSUE TITLE
debug-shell broken

### ISSUE THREAD

**Issue by clstb** [danisla/kubefunc#4]
❯ k debug-shell
error: --rm should only be used for attached containers
See 'kubectl run -h' for help and examples.

kubectl: Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Tested in fish and bash.

**Comment by jrnt30** [comment]
The newer versions of the Kubectl CLI have stopped providing `KUBECTL_PLUGINS_CURRENT_NAMESPACE` which breaks the configuration. 

https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#flags-and-argument-handling

**Comment by jamiecyber** [comment]
~/Coding $ KUBECTL_PLUGINS_CURRENT_NAMESPACE=mynamespace kubectl debug-shell ubuntu
If you don't see a command prompt, try pressing enter.
root@kube-shell:/#

**Comment by yashbhutwala** [comment]
What's the point of this plugin?
